services:
  - type: web
    name: study-buddy-api
    env: node
    region: singapore
    plan: free
    rootDir: server
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: JWT_SECRET
        sync: false
      - key: DB_HOST
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_NAME
        sync: false
      - key: DB_PORT
        value: 3306
      - key: CLIENT_URL
        sync: false
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false
      - key: PAYHERE_MERCHANT_ID
        sync: false
      - key: PAYHERE_MERCHANT_SECRET
        sync: false
