const db = require('../config/db');

// Mark Attendance (Tutor scans Student QR)
const markAttendance = async (req, res) => {
    let { studentId, subjectId, status, sessionId } = req.body;
    const teacherId = req.user.id;

    // SECURITY: Ignore client date. Use Server Date.
    const now = new Date();
    const serverDate = now.toISOString().split('T')[0];

    if (!studentId || !subjectId) {
        return res.status(400).json({ message: "Missing required fields" });
    }

    try {
        // 1. Verify Student Exists
        const [student] = await db.query("SELECT * FROM Student WHERE StudentID = ?", [studentId]);
        if (student.length === 0) return res.status(404).json({ message: "Student not found" });

        // 2. Find or Create Session
        // Check for 'virtual' session ID (generated by frontend/backend for timetable slots)
        if (sessionId && !sessionId.toString().startsWith('virtual_')) {
            // Validate Session Matches Subject
            const [explicitSession] = await db.query(`
                SELECT s.* FROM Session s
                JOIN SubjectGrade sg ON s.SubjectGradeID = sg.SubjectGradeID
                WHERE s.SessionID = ? AND s.TeacherID = ? AND sg.SubjectID = ?
            `, [sessionId, teacherId, subjectId]);

            if (explicitSession.length === 0) {
                return res.status(404).json({ message: "Invalid Session ID or Session mismatch." });
            }
        }
        else {
            // CASE B: Implicit / Quick Scan OR Virtual Session Confirmation
            const studentGrade = student[0].Grade;

            // Find existing session for Today + Subject + Grade
            const [existingSession] = await db.query(`
                SELECT s.* FROM Session s
                JOIN SubjectGrade sg ON s.SubjectGradeID = sg.SubjectGradeID
                WHERE s.TeacherID = ? AND sg.SubjectID = ? AND sg.Grade = ? AND s.Date = ?
            `, [teacherId, subjectId, studentGrade, serverDate]);

            if (existingSession.length > 0) {
                sessionId = existingSession[0].SessionID;
            } else {
                // Create new Session for TODAY
                console.log(`Creating ad-hoc session for ${serverDate}`);

                // Need SubjectGradeID
                const [sgRows] = await db.query("SELECT SubjectGradeID FROM SubjectGrade WHERE SubjectID = ? AND Grade = ?", [subjectId, studentGrade]);
                if (sgRows.length === 0) return res.status(400).json({ message: "No Subject-Grade found for this student's grade." });
                const subjectGradeId = sgRows[0].SubjectGradeID;

                sessionId = 'SE' + Date.now().toString().slice(-6);
                await db.query(
                    "INSERT INTO Session (SessionID, TeacherID, SubjectGradeID, Date, StartTime, EndTime) VALUES (?, ?, ?, ?, ?, ?)",
                    [sessionId, teacherId, subjectGradeId, serverDate, '00:00:00', '00:00:00']
                );
            }
        }

        // 3. Mark Attendance
        // Check if already marked for THIS session
        const [existingAttendance] = await db.query(
            "SELECT * FROM Attendance WHERE SessionID = ? AND StudentID = ?",
            [sessionId, studentId]
        );

        if (existingAttendance.length > 0) {
            return res.status(400).json({ message: "Attendance already marked for this session." });
        }

        const attendanceId = 'AT' + Date.now().toString().slice(-6);
        await db.query(
            "INSERT INTO Attendance (AttendanceID, SessionID, StudentID, Status, ScannedAt) VALUES (?, ?, ?, ?, NOW())",
            [attendanceId, sessionId, studentId, status || 'Present']
        );

        res.json({
            message: "Attendance marked successfully",
            studentName: student[0].StudentName,
            subjectId: subjectId,
            sessionId: sessionId,
            date: serverDate
        });

    } catch (err) {
        console.error("Mark Attendance Error:", err.message, err.stack);
        res.status(500).json({ message: "Server Error marking attendance", error: err.message });
    }
};

const getTeacherSubjects = async (req, res) => {
    const teacherId = req.user.id;
    try {
        const [subjects] = await db.query(`
            SELECT s.SubjectID, s.SubjectName 
            FROM TeacherSubject ts 
            JOIN Subject s ON ts.SubjectID = s.SubjectID 
            WHERE ts.TeacherID = ?
        `, [teacherId]);
        res.json(subjects);
    } catch (err) {
        console.error(err);
        res.status(500).json({ message: "Error fetching subjects" });
    }
};

// Get Teacher's Schedule (Sessions)
const getTeacherSessions = async (req, res) => {
    const teacherId = req.user.id;
    try {
        const [sessions] = await db.query(`
            SELECT s.*, sub.SubjectName, sg.Grade
            FROM Session s
            JOIN SubjectGrade sg ON s.SubjectGradeID = sg.SubjectGradeID
            JOIN Subject sub ON sg.SubjectID = sub.SubjectID
            WHERE s.TeacherID = ?
            AND s.Date >= CURRENT_DATE
            ORDER BY s.Date, s.StartTime
        `, [teacherId]);
        res.json(sessions);
    } catch (err) {
        console.error(err);
        res.status(500).json({ message: "Error fetching sessions" });
    }
};

// Get Student Attendance (Overall or by Subject)
const getStudentAttendance = async (req, res) => {
    const { studentId } = req.params;
    const { subjectId } = req.query; // Optional filter

    try {
        let query = `
            SELECT a.*, s.Date, s.StartTime, s.EndTime, sub.SubjectName, sg.Grade
            FROM Attendance a
            JOIN Session s ON a.SessionID = s.SessionID
            JOIN SubjectGrade sg ON s.SubjectGradeID = sg.SubjectGradeID
            JOIN Subject sub ON sg.SubjectID = sub.SubjectID
            WHERE a.StudentID = ?
        `;
        const params = [studentId];

        if (subjectId) {
            query += " AND sg.SubjectID = ?";
            params.push(subjectId);
        }

        query += " ORDER BY s.Date DESC";

        const [records] = await db.query(query, params);
        res.json(records);
    } catch (err) {
        console.error(err);
        res.status(500).json({ message: "Error fetching attendance" });
    }
};

// NEW: Get Teacher Modules (Classes) - Grouped by Subject, with available Grades
const getTeacherClasses = async (req, res) => {
    const teacherId = req.user.id;
    try {
        // Fetch Subjects, Grades, and Student Counts in one efficient query
        const [classes] = await db.query(`
            SELECT 
                s.SubjectID, 
                s.SubjectName, 
                sg.Grade, 
                COUNT(e.EnrollmentID) as StudentCount
            FROM TeacherSubject ts
            JOIN Subject s ON ts.SubjectID = s.SubjectID
            JOIN SubjectGrade sg ON s.SubjectID = sg.SubjectID
            LEFT JOIN Enrollment e ON sg.SubjectGradeID = e.SubjectGradeID
            WHERE ts.TeacherID = ?
            GROUP BY s.SubjectID, s.SubjectName, sg.Grade
            HAVING StudentCount > 0 OR sg.Grade IN (6, 7, 8, 9) -- Limit to relevant grades if count is 0
            ORDER BY s.SubjectName, sg.Grade
        `, [teacherId]);

        // Filter to ensure we only show valid grades (Optional: strict logic)
        // For now, the query returns all Subject-Grade combinations for the teacher's subjects.
        // If we want to strictly show only grades 6-9 as per seed:
        const startUpClasses = classes.filter(c => [6, 7, 8, 9].includes(c.Grade));

        res.json(startUpClasses);
    } catch (err) {
        console.error(err);
        res.status(500).json({ message: "Error fetching classes" });
    }
};

// NEW: Get Students for a specific Class (Subject + Grade)
const getClassStudents = async (req, res) => {
    const { subjectId, grade } = req.params;
    try {
        const [students] = await db.query(`
            SELECT s.StudentID, s.StudentName, s.Grade, s.ParentID, u.FullName as ParentName, pp.Phone as ParentPhone, e.EnrolledDate,
            (
                SELECT GROUP_CONCAT(sub2.SubjectName SEPARATOR ', ')
                FROM Enrollment e2
                JOIN SubjectGrade sg2 ON e2.SubjectGradeID = sg2.SubjectGradeID
                JOIN Subject sub2 ON sg2.SubjectID = sub2.SubjectID
                WHERE e2.StudentID = s.StudentID
            ) as EnrolledSubjects
            FROM Student s
            JOIN Enrollment e ON s.StudentID = e.StudentID
            JOIN SubjectGrade sg ON e.SubjectGradeID = sg.SubjectGradeID
            LEFT JOIN ParentProfile pp ON s.ParentID = pp.UserID
            LEFT JOIN User u ON s.ParentID = u.UserID
            WHERE sg.SubjectID = ? AND sg.Grade = ?
        `, [subjectId, grade]);
        res.json(students);
    } catch (err) {
        console.error(err);
        res.status(500).json({ message: "Error fetching students" });
    }
};

// NEW: Create Manual Session
const createManualSession = async (req, res) => {
    const { subjectId, grade, date, startTime, endTime } = req.body;
    const teacherId = req.user.id;

    if (!subjectId || !grade || !date || !startTime || !endTime) {
        return res.status(400).json({ message: "All fields are required" });
    }

    try {
        // Resolve SubjectGradeID
        const [rows] = await db.query("SELECT SubjectGradeID FROM SubjectGrade WHERE SubjectID = ? AND Grade = ?", [subjectId, grade]);
        if (rows.length === 0) return res.status(400).json({ message: "Invalid Subject-Grade combination" });
        const subjectGradeId = rows[0].SubjectGradeID;

        const sessionId = 'SE_MAN_' + Date.now().toString().slice(-6);
        await db.query(
            "INSERT INTO Session (SessionID, TeacherID, SubjectGradeID, Date, StartTime, EndTime) VALUES (?, ?, ?, ?, ?, ?)",
            [sessionId, teacherId, subjectGradeId, date, startTime, endTime]
        );
        res.status(201).json({ message: "Session created successfully", sessionId });
    } catch (err) {
        console.error("Error creating session manually:", err);
        res.status(500).json({ message: "Error creating session: " + err.message });
    }
};

// NEW: Get Sessions for a Specific Class (Subject + Grade) - For Attendance Tab
// Includes BOTH Explicit Sessions and Virtual Timetable Slots
const getClassSessions = async (req, res) => {
    const { subjectId, grade } = req.params;
    const teacherId = req.user.id;

    try {
        // 1. Fetch Explicit Sessions (Manual or Attended)
        const [explicitSessions] = await db.query(`
            SELECT s.* 
            FROM Session s
            JOIN SubjectGrade sg ON s.SubjectGradeID = sg.SubjectGradeID
            WHERE sg.SubjectID = ? AND sg.Grade = ? AND s.TeacherID = ?
            ORDER BY s.Date ASC, s.StartTime ASC
        `, [subjectId, grade, teacherId]);

        // 2. Fetch Timetable Entries
        const [timetable] = await db.query(`
            SELECT t.*
            FROM Timetable t
            JOIN SubjectGrade sg ON t.SubjectGradeID = sg.SubjectGradeID
            WHERE sg.SubjectID = ? AND sg.Grade = ? AND t.TeacherID = ?
        `, [subjectId, grade, teacherId]);

        // 3. Generate Virtual Sessions for Current Month
        const combinedSessions = [...explicitSessions];

        if (timetable.length > 0) {
            const today = new Date();
            const startOfMonth = new Date(today.getFullYear(), today.getMonth(), 1);
            const endOfMonth = new Date(today.getFullYear(), today.getMonth() + 1, 0);

            const dayMap = { 'Sunday': 0, 'Monday': 1, 'Tuesday': 2, 'Wednesday': 3, 'Thursday': 4, 'Friday': 5, 'Saturday': 6 };

            // Loop through each day of the month
            for (let d = new Date(startOfMonth); d <= endOfMonth; d.setDate(d.getDate() + 1)) {
                const dayName = d.toLocaleDateString('en-US', { weekday: 'long' });
                const dateStr = d.toISOString().split('T')[0];

                // Check for timetable slots for this day
                const slots = timetable.filter(t => t.DayOfWeek === dayName);

                slots.forEach(slot => {
                    // Check if explicit session already exists for this Date + StartTime (approx check)
                    const exists = explicitSessions.some(es => es.Date.toISOString().split('T')[0] === dateStr); // Simple check: one session per day per class assumption? 
                    // Better check: allow multiple times? Use StartTime check?
                    // Assuming Timetable is the source of truth for "Planned", Session is "Actual".
                    // If an Actual session exists for that DATE, we assume it replaces the Timetable slot(s) OR is the realization of it.
                    // Let's assume strict uniqueness on Date to avoid clutter, as per simplified requirements.

                    if (!exists) {
                        combinedSessions.push({
                            SessionID: `virtual_${dateStr}_${slot.StartTime}`, // Virtual ID
                            TeacherID: teacherId,
                            SubjectGradeID: slot.SubjectGradeID, // Propagate
                            Date: new Date(dateStr), // ensure Date object
                            StartTime: slot.StartTime,
                            EndTime: slot.EndTime,
                            IsVirtual: true // Marker
                        });
                    }
                });
            }
        }

        // 4. Sort Combined List
        combinedSessions.sort((a, b) => new Date(a.Date) - new Date(b.Date) || a.StartTime.localeCompare(b.StartTime));

        res.json(combinedSessions);
    } catch (err) {
        console.error(err);
        res.status(500).json({ message: "Error fetching class sessions" });
    }
};
// NEW: Get Attendance for a Specific Session (List of Students Present)
const getSessionAttendance = async (req, res) => {
    const { sessionId } = req.params;
    try {
        const [attendance] = await db.query(`
            SELECT a.*, s.StudentName, s.StudentID 
            FROM Attendance a
            JOIN Student s ON a.StudentID = s.StudentID
            WHERE a.SessionID = ?
            ORDER BY s.StudentName ASC
        `, [sessionId]);
        res.json(attendance);
    } catch (err) {
        console.error("Error fetching session attendance:", err);
        res.status(500).json({ message: "Error fetching attendance list" });
    }
};

module.exports = { markAttendance, getTeacherSubjects, getStudentAttendance, getTeacherSessions, getTeacherClasses, getClassStudents, createManualSession, getClassSessions, getSessionAttendance };
